basePath: /api/v1
definitions:
  web.response:
    properties:
      code:
        type: integer
      data: {}
      error:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: Goesgil
    url: http://www.example.com
  license:
    name: Apache 2.0
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /transactions:
    post:
      consumes:
      - application/json
      description: Create a new transaction
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            type: ""
        "401":
          description: Unauthorized
          schema:
            type: ""
        "500":
          description: Internal Server Error
          schema:
            type: ""
      security:
      - token header string "Bearer <token>": []
      summary: Transactions
      tags:
      - trxs
  /transactions/{id}:
    delete:
      consumes:
      - application/json
      description: Update codeTrxs and amount of a transaction
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.response'
      security:
      - token header string "Bearer <token>": []
      summary: Transactions
      tags:
      - trxs
    patch:
      consumes:
      - application/json
      description: Update codeTrxs and amount of a transaction
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.response'
      security:
      - token header string "Bearer <token>": []
      summary: Transactions
      tags:
      - trxs
    put:
      consumes:
      - application/json
      description: Update a transaction
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.response'
      security:
      - token header string "Bearer <token>": []
      summary: Transactions
      tags:
      - trxs
swagger: "2.0"
